// Sidebar Routers
export const menus = {
    "message.general": [
        {
            action: "zmdi-case",
            title: "message.clients",
            path: "/clients",
            module: "client",
            active: false,
            items: null,
            exact: true,
        },
        {
            action: "zmdi-account-circle",
            title: "message.users",
            path: "/users",
            module: "user",
            active: false,
            items: null,
            exact: true,
        },
        {
            action: "zmdi-pin",
            title: "message.locations",
            path: "/locations",
            module: "location",
            active: false,
            items: null,
            exact: true,
        },
        {
            action: "zmdi-account",
            title: "message.patients",
            path: "/patients",
            module: "patient",
            active: false,
            items: null,
            exact: true,
        },
        {
            action: "zmdi-accounts-list-alt",
            title: "message.contacts",
            path: "/contacts",
            module: "contact",
            active: false,
            items: null,
            exact: true,
        },
        {
            action: "zmdi-notifications",
            title: "message.alerts",
            path: "/alerts",
            module: "alert",
            active: false,
            items: null,
            exact: true,
        },
        {
            action: "zmdi-settings",
            title: "message.settings",
            path: "/settings",
            module: "settings",
            active: false,
            items: null,
            exact: true,
        },
        {
            action: "zmdi-comments",
            title: "Chat",
            path: "/chat",
            module: "chat",
            active: false,
            items: null,
            exact: true,
        },
        {
            action: "zmdi-collection-text",
            title: "message.forms",
            path: "/forms",
            module: "form_builder",
            active: true,
            items: null,
            exact: true,
        },
    ],
};
